// import { customerData } from "@/data";
// import { useParams } from "next/navigation";
// import MainLayout from "@/components/common/layouts/MainLayout";
// import styles from "@/styles/customerDetail.module.css";
// import Image from "next/image";
// import Head from "next/head";
// import Grid from "@mui/material/Grid";
// import { useRouter } from "next/router";
// import { useState, useEffect } from "react";

// function CustomerDetail() {
//   const router = useRouter();
//   const [currentCustomer, setCurrentCustomer] = useState(null);
//   const [activeFilter, setActiveFilter] = useState("Monthly");
//   const [mostLikedFilter, setMostLikedFilter] = useState("Monthly");

//   // useEffect(() => {
//   //   if (router.query.id) {
//   //     setCurrentCustomer(customerData.find((o) => o.id === router.query.id));
//   //   }
//   // }, [router]);
//   useEffect(() => {
//     const toptop = customerData.find((cus) => cus.id == router.query.id);
//     console.log(router);
//     setCurrentCustomer(toptop);
//   }, [router]);

//   return (
//     <>
//       <Head>
//         <title>
//           {currentCustomer
//             ? "Customer ID: " + currentCustomer.id
//             : "Customer not found"}
//         </title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {currentCustomer ? (
//         <div className={styles["container"]}>
//           <div className={styles["cusDetailHead"]}>
//             <h1>Customer Detail</h1>
//             <p>Here your Customer Detail Profile</p>
//           </div>
//           <Grid container spacing={4} sx={{ alignItems: "center" }}>
//             <Grid size={8}>
//               <div className={styles["userAbout"]}>
//                 {/* <Image src={} alt="" width={} height={}/> */}
//                 <div
//                   style={{
//                     width: "222px",
//                     height: "222px",
//                     borderRadius: "22px",
//                     backgroundColor: "gray",
//                     marginRight: "30px",
//                   }}
//                 ></div>
//                 <div className={styles["names"]}>
//                   <div className={styles["namesHead"]}>
//                     <div className={styles["nameAndLoc"]}>
//                       <h3>{currentCustomer.name}</h3>
//                       <p>{currentCustomer.job}</p>
//                       <p>{currentCustomer.homeLocation}</p>
//                     </div>
//                     <div className={styles["btns"]}>
//                       <button>
//                         <Image
//                           src="/question.png"
//                           alt="question"
//                           width={28}
//                           height={28}
//                         />
//                       </button>
//                       <button>
//                         <Image
//                           src="/pencil.png"
//                           alt=""
//                           width={28}
//                           height={28}
//                         />
//                       </button>
//                     </div>
//                   </div>
//                   <div className={styles["namesFooter1"]}>
//                     <div className={styles["emailNumJob"]}>
//                       <button>
//                         <Image
//                           src="/messange.png"
//                           alt=""
//                           width={20}
//                           height={20}
//                         />
//                       </button>
//                       <p>{currentCustomer.email}</p>
//                     </div>
//                     <div className={styles["emailNumJob1"]}>
//                       <button>
//                         <Image src="/phone.png" alt="" width={20} height={20} />
//                       </button>
//                       <p>{currentCustomer.phone}</p>
//                     </div>
//                     <div className={styles["emailNumJob2"]}>
//                       <button>
//                         <Image src="/bag.png" alt="" width={20} height={20} />
//                       </button>
//                       <p>{currentCustomer.companyName}</p>
//                     </div>
//                   </div>
//                 </div>
//               </div>
//             </Grid>
//             <Grid size={4}>
//               <div className={styles["cartAbout"]}>
//                 <div
//                   style={{
//                     display: "flex",
//                     justifyContent: "space-between",
//                     color: "white",
//                     padding: "0px 36px 0px 38px",
//                   }}
//                 >
//                   <p>Your Balance</p>
//                   <button
//                     style={{
//                       background: "unset",
//                       border: "none",
//                       cursor: "pointer",
//                     }}
//                   >
//                     <Image src="/dot.png" alt="" width={31} height={25} />
//                   </button>
//                 </div>
//                 <p
//                   style={{
//                     fontSize: "52px",
//                     color: "white",
//                     padding: "10px 36px 10px 38px",
//                   }}
//                 >
//                   $ {currentCustomer.userCard.cardBalans}
//                 </p>
//                 <div
//                   style={{
//                     display: "flex",
//                     justifyContent: "space-between",
//                     color: "white",
//                     fontSize: "21px",
//                     padding: "0px 36px 26px 38px",
//                     marginBottom: "10px",
//                   }}
//                 >
//                   <p>{currentCustomer.userCard.cardNumber}</p>
//                   <p>{currentCustomer.userCard.cardDate}</p>
//                 </div>
//                 <div
//                   style={{
//                     display: "flex",
//                     justifyContent: "space-between",
//                     backgroundColor: "#40134726",
//                     width: "100%",
//                     padding: "21px 36px 18px 38px",
//                   }}
//                 >
//                   <div className={styles["cardName"]}>
//                     <p>Name</p>
//                     <p>{currentCustomer.userCard.cardName}</p>
//                   </div>
//                   <Image src="/name-card.png" alt="" width={60} height={56} />
//                 </div>
//               </div>
//             </Grid>
//           </Grid>
//           <div className={styles["cusDetailFooter"]}>
//             <div className={styles["mostOrderedFood"]}>
//               <div className={styles["btnAndName"]}>
//                 <div className={styles["mostOrdered"]}>
//                   <p>Most Ordered Food</p>
//                   <p>Lorem ipsum dolor sit amet, consectetur</p>
//                 </div>
//                 <div className={styles["mostOrderBtns"]}>
//                   <button
//                     className={activeFilter === "Monthly" ? styles.active : ""}
//                     onClick={() => setActiveFilter("Monthly")}
//                   >
//                     Monthly
//                   </button>
//                   <button
//                     className={activeFilter === "Weekly" ? styles.active : ""}
//                     onClick={() => setActiveFilter("Weekly")}
//                   >
//                     Weekly
//                   </button>
//                   <button
//                     className={activeFilter === "Daily" ? styles.active : ""}
//                     onClick={() => setActiveFilter("Daily")}
//                   >
//                     Daily
//                   </button>
//                 </div>
//               </div>
//               {currentCustomer.items.map((item) => (
//                 <Order key={currentCustomer.id} item={item} />
//               ))}
//             </div>
//             <div className={styles["mostLokedFood"]}>
//               <div className={styles["btnAndName"]}>
//                 <div className={styles["mostOrdered"]}>
//                   <p>Most Liked Food</p>
//                   <p>Lorem ipsum dolor sit amet, consectetur</p>
//                 </div>
//                 <div className={styles["mostOrderBtns"]}>
//                   <button
//                     className={
//                       mostLikedFilter === "Monthly" ? styles.active : ""
//                     }
//                     onClick={() => setMostLikedFilter("Monthly")}
//                   >
//                     Monthly
//                   </button>
//                   <button
//                     className={
//                       mostLikedFilter === "Weekly" ? styles.active : ""
//                     }
//                     onClick={() => setMostLikedFilter("Weekly")}
//                   >
//                     Weekly
//                   </button>
//                   <button
//                     className={mostLikedFilter === "Daily" ? styles.active : ""}
//                     onClick={() => setMostLikedFilter("Daily")}
//                   >
//                     Daily
//                   </button>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </div>
//       ) : (
//         <div>
//           <p>Customer not found</p>
//         </div>
//       )}
//     </>
//   );
// }

// export default CustomerDetail;

// function Order(props) {
//   const { item } = props;
//   return (
//     <div
//       style={{
//         padding: "12px 30px",
//         width: "100%",
//         display: "flex",
//         justifyContent: "space-between",
//         alignItems: "center",
//       }}
//     >
//       {/* <Image src="" alt="" width={} height={} /> */}
//       <div style={{ display: "flex" }}>
//         <div
//           style={{
//             borderRadius: "16px",
//             background: "#B9BBBD",
//             width: "87px",
//             height: "87px",
//           }}
//         ></div>
//         <div className={styles["middle"]}>
//           <p>{item.foodName}</p>
//           <p>{item.food}</p>
//           <p>
//             Serves for {item.person} Person | {item.min}mins
//           </p>
//         </div>
//       </div>
//       <div className={styles["priceBtn"]}>
//         <p>${item.price}</p>
//         <button
//           style={{
//             background: "unset",
//             border: "none",
//             marginLeft: "32px",
//             cursor: "pointer",
//           }}
//         >
//           <Image src="/dots.png" alt="" width={24} height={24} />
//         </button>
//       </div>
//     </div>
//   );
// }

// CustomerDetail.getLayout = (pageProps) => (
//   <MainLayout>
//     <CustomerDetail {...pageProps} />
//   </MainLayout>
// );
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
import { customerData } from "@/data";
import { useParams } from "next/navigation";
import MainLayout from "@/components/common/layouts/MainLayout";
import Image from "next/image";
import Head from "next/head";
import Grid from "@mui/material/Grid";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

function CustomerDetail() {
  const router = useRouter();
  const [currentCustomer, setCurrentCustomer] = useState(null);
  const [activeFilter, setActiveFilter] = useState("Monthly");
  const [mostLikedFilter, setMostLikedFilter] = useState("Monthly");

  useEffect(() => {
    const toptop = customerData.find((cus) => cus.id == router.query.id);
    setCurrentCustomer(toptop);
  }, [router]);

  return (
    <>
      <Head>
        <title>
          {currentCustomer
            ? "Customer ID: " + currentCustomer.id
            : "Customer not found"}
        </title>
      </Head>
      {currentCustomer ? (
        <div
          style={{
            width: "100%",
            maxWidth: "1468px",
            margin: "0 auto",
          }}
        >
          <div style={{ marginBottom: "40px" }}>
            <h1 style={{ fontSize: "32px", color: "#464255" }}>
              Customer Detail
            </h1>
            <p style={{ fontSize: "18px", color: "#a3a3a3" }}>
              Here your Customer Detail Profile
            </p>
          </div>

          <Grid container spacing={4} alignItems="center">
            <Grid item xs={12} md={8}>
              <div
                style={{
                  display: "flex",
                  backgroundColor: "#fdfdfd",
                  border: "1px solid rgb(236, 236, 236)",
                  padding: "30px",
                  borderRadius: "16px",
                }}
              >
                <div
                  style={{
                    width: "222px",
                    height: "222px",
                    borderRadius: "22px",
                    backgroundColor: "gray",
                    marginRight: "30px",
                  }}
                ></div>
                <div style={{ width: "100%" }}>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                    }}
                  >
                    <div>
                      <h3
                        style={{
                          fontSize: "36px",
                          color: "#464255",
                          padding: "11px 0px 15px 0px",
                        }}
                      >
                        {currentCustomer.name}
                      </h3>
                      <p
                        style={{
                          fontSize: "21px",
                          color: "#00b074",
                          paddingBottom: "20px",
                        }}
                      >
                        {currentCustomer.job}
                      </p>
                      <p style={{ fontSize: "14px", color: "#a3a3a3" }}>
                        {currentCustomer.homeLocation}
                      </p>
                    </div>
                    <div>
                      <button
                        style={{
                          padding: "16px",
                          backgroundColor: "#00b07426",
                          borderRadius: "20px",
                          border: "none",
                          cursor: "pointer",
                        }}
                      >
                        <Image
                          src="/question.png"
                          alt="question"
                          width={28}
                          height={28}
                        />
                      </button>
                      <button
                        style={{
                          padding: "16px",
                          backgroundColor: "#5e6c9326",
                          border: "none",
                          marginLeft: "20px",
                          cursor: "pointer",
                          borderRadius: "20px",
                        }}
                      >
                        <Image
                          src="/pencil.png"
                          alt=""
                          width={28}
                          height={28}
                        />
                      </button>
                    </div>
                  </div>

                  <div
                    style={{
                      width: "100%",
                      margin: "35px 0px 17px 0px",
                      display: "flex",
                      justifyContent: "space-between",
                    }}
                  >
                    <div style={{ display: "flex", alignItems: "center" }}>
                      <button
                        style={{
                          padding: "5px",
                          backgroundColor: "#2d9cdb26",
                          borderRadius: "8px",
                          border: "none",
                          cursor: "pointer",
                          marginRight: "16px",
                        }}
                      >
                        <Image
                          src="/messange.png"
                          alt=""
                          width={20}
                          height={20}
                        />
                      </button>
                      <p>{currentCustomer.email}</p>
                    </div>
                    <div style={{ display: "flex", alignItems: "center" }}>
                      <button
                        style={{
                          marginLeft: "30px",
                          padding: "5px",
                          backgroundColor: "#00b07426",
                          borderRadius: "8px",
                          border: "none",
                          cursor: "pointer",
                          marginRight: "16px",
                        }}
                      >
                        <Image src="/phone.png" alt="" width={20} height={20} />
                      </button>
                      <p>{currentCustomer.phone}</p>
                    </div>
                    <div style={{ display: "flex", alignItems: "center" }}>
                      <button
                        style={{
                          padding: "5px",
                          marginLeft: "30px",
                          backgroundColor: "#ff5b5b26",
                          borderRadius: "8px",
                          border: "none",
                          cursor: "pointer",
                          marginRight: "16px",
                        }}
                      >
                        <Image src="/bag.png" alt="" width={20} height={20} />
                      </button>
                      <p>{currentCustomer.companyName}</p>
                    </div>
                  </div>
                </div>
              </div>
            </Grid>

            <Grid item xs={12} md={4}>
              <div
                style={{
                  width: "100%",
                  borderRadius: "16px",
                  backgroundColor: "#00b074",
                  padding: "25px 0px 0px 0px",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    color: "white",
                    padding: "0px 36px 0px 38px",
                  }}
                >
                  <p>Your Balance</p>
                  <button
                    style={{
                      background: "unset",
                      border: "none",
                      cursor: "pointer",
                    }}
                  >
                    <Image src="/dot.png" alt="" width={31} height={25} />
                  </button>
                </div>
                <p
                  style={{
                    fontSize: "52px",
                    color: "white",
                    padding: "10px 36px 10px 38px",
                  }}
                >
                  $ {currentCustomer.userCard.cardBalans}
                </p>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    color: "white",
                    fontSize: "21px",
                    padding: "0px 36px 26px 38px",
                    marginBottom: "10px",
                  }}
                >
                  <p>{currentCustomer.userCard.cardNumber}</p>
                  <p>{currentCustomer.userCard.cardDate}</p>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    backgroundColor: "#40134726",
                    width: "100%",
                    padding: "21px 36px 18px 38px",
                  }}
                >
                  <div>
                    <p
                      style={{
                        color: "white",
                        fontSize: "14px",
                        marginBottom: "3px",
                      }}
                    >
                      Name
                    </p>
                    <p style={{ color: "white", fontSize: "21px" }}>
                      {currentCustomer.userCard.cardName}
                    </p>
                  </div>
                  <Image src="/name-card.png" alt="" width={60} height={56} />
                </div>
              </div>
            </Grid>
          </Grid>

          <div
            style={{
              width: "100%",
              marginTop: "40px",
              display: "flex",
              justifyContent: "space-between",
            }}
          >
            <div
              style={{
                width: "713px",
                borderRadius: "24px",
                border: "1px solid rgb(236, 236, 236)",
                backgroundColor: "#fdfdfd",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: "25px",
                  padding: "35px 48px 0px",
                }}
              >
                <div>
                  <p
                    style={{
                      fontSize: "21px",
                      color: "#464255",
                      marginBottom: "12px",
                    }}
                  >
                    Most Ordered Food
                  </p>
                  <p style={{ fontSize: "12px", color: "#a3a3a3" }}>
                    Lorem ipsum dolor sit amet, consectetur
                  </p>
                </div>
                <div
                  style={{
                    width: "270px",
                    backgroundColor: "#f3f2f7",
                    borderRadius: "24px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    padding: "6px",
                  }}
                >
                  {["Monthly", "Weekly", "Daily"].map((filter) => (
                    <button
                      key={filter}
                      onClick={() => setActiveFilter(filter)}
                      style={{
                        padding: "7px 18px",
                        borderRadius: "57px",
                        border: "none",
                        fontSize: "15px",
                        cursor: "pointer",
                        backgroundColor:
                          activeFilter === filter ? "#ffffff" : "transparent",
                      }}
                    >
                      {filter}
                    </button>
                  ))}
                </div>
              </div>

              {currentCustomer.items.map((item, i) => (
                <Order key={i} item={item} />
              ))}
            </div>

            <div
              style={{
                width: "713px",
                borderRadius: "24px",
                border: "1px solid rgb(236, 236, 236)",
                backgroundColor: "#fdfdfd",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: "25px",
                  padding: "35px 48px 0px",
                }}
              >
                <div>
                  <p
                    style={{
                      fontSize: "21px",
                      color: "#464255",
                      marginBottom: "12px",
                    }}
                  >
                    Most Liked Food
                  </p>
                  <p style={{ fontSize: "12px", color: "#a3a3a3" }}>
                    Lorem ipsum dolor sit amet, consectetur
                  </p>
                </div>
                <div
                  style={{
                    width: "270px",
                    backgroundColor: "#f3f2f7",
                    borderRadius: "24px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    padding: "6px",
                  }}
                >
                  {["Monthly", "Weekly", "Daily"].map((filter) => (
                    <button
                      key={filter}
                      onClick={() => setMostLikedFilter(filter)}
                      style={{
                        padding: "7px 18px",
                        borderRadius: "57px",
                        border: "none",
                        fontSize: "15px",
                        cursor: "pointer",
                        backgroundColor:
                          mostLikedFilter === filter
                            ? "#ffffff"
                            : "transparent",
                      }}
                    >
                      {filter}
                    </button>
                  ))}
                </div>
              </div>
              {/* You can map liked items here too */}
            </div>
          </div>
        </div>
      ) : (
        <div>
          <p>Customer not found</p>
        </div>
      )}
    </>
  );
}

export default CustomerDetail;

function Order({ item }) {
  return (
    <div
      style={{
        padding: "12px 30px",
        width: "100%",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
      }}
    >
      <div style={{ display: "flex" }}>
        <div
          style={{
            borderRadius: "16px",
            background: "#B9BBBD",
            width: "87px",
            height: "87px",
          }}
        ></div>
        <div style={{ maxWidth: "329px", marginLeft: "24px" }}>
          <p
            style={{
              fontSize: "16px",
              color: "#464255",
              marginBottom: "9px",
              fontWeight: "700",
            }}
          >
            {item.foodName}
          </p>
          <p
            style={{ fontSize: "12px", color: "#2d9cdb", marginBottom: "17px" }}
          >
            {item.food}
          </p>
          <p style={{ fontSize: "12px", color: "#a3a3a3" }}>
            Serves for {item.person} Person | {item.min} mins
          </p>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center" }}>
        <p>${item.price}</p>
        <button
          style={{
            background: "unset",
            border: "none",
            marginLeft: "32px",
            cursor: "pointer",
          }}
        >
          <Image src="/dots.png" alt="" width={24} height={24} />
        </button>
      </div>
    </div>
  );
}

CustomerDetail.getLayout = (pageProps) => (
  <MainLayout>
    <CustomerDetail {...pageProps} />
  </MainLayout>
);
