// import { useParams } from "next/navigation";
// import orderListData from "@/data";
// import Head from "next/head";
// import PageTitle from "@/components/common/PageTitle";
// import styles from "@/styles/orderDetail.module.css";
// import MainLayout from "@/components/common/layouts/MainLayout";
// import Image from "next/image";
// import CustomizedTables from "@/components/common/detailTable";
// import { useEffect, useState } from "react";
// import Grid from "@mui/material/Grid";

// function OrderDetail() {
//   const route = useParams();
//   const currentOrder = orderListData.find((item) => {
//     if (item.userId === parseInt(route?.id)) {
//       return true;
//     }
//   });
//   const [orders, setOrders] = useState([]);
//   useEffect(() => {
//     const savedOrders = localStorage.getItem("orders");
//     if (savedOrders) {
//       setOrders(JSON.parse(savedOrders));
//     }
//   }, []);

//   console.log(orders);
//   return (
//     <>
//       <Head>
//         <title>Orders Page</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="container">
//         <div
//           style={{
//             width: "100%",
//           }}
//         >
//           <div
//             style={{
//               marginBottom: "40px",
//             }}
//           >
//             <div
//               style={{
//                 maxWidth: "1468px",
//                 display: "flex",
//                 alignItems: "center",
//                 justifyContent: "space-between",
//               }}
//             >
//               <PageTitle
//                 title="Order ID # "
//                 subtitle="Orders / Order Detaills"
//                 id={orders.userId}
//               />
//               <div>
//                 <button className={styles.cancelBtn}>Cancel Order</button>
//                 <button className={styles.onDelivery}>On Delivery</button>
//               </div>
//             </div>
//           </div>
//           <div style={{ display: "flex", alignItems: "start", gap: "40px" }}>
//             <div className={styles.leftDiv}>
//               <div className={styles.leftTop}>
//                 <div className={styles.forAvatar}></div>
//                 <h2>{orders.userName}</h2>
//                 <p className={styles.type}>{orders.type}</p>
//                 <div className={styles.noteOrder}>
//                   <h3>Note Order</h3>
//                   <p>
//                     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
//                     do eiusmod tempor incididunt ut labore et dolore magna
//                     aliqua.
//                   </p>
//                   <div className={styles.noteOrderDelivery}>
//                     <Image
//                       src="/shipping.png"
//                       alt="icon"
//                       width={50}
//                       height={50}
//                     />
//                     <p>
//                       6 The Avenue, London <br />
//                       EC50 4GN
//                     </p>
//                   </div>
//                 </div>
//               </div>
//               <div className={styles.leftBottom}>
//                 <Image
//                   src="/detailBottomLeft.png"
//                   width={211}
//                   height={366}
//                   alt="img"
//                 />
//               </div>
//             </div>
//             <div className={styles.rightDiv}>
//               <div className={styles.rightTop}>
//                 <CustomizedTables data={orders.orders} />
//               </div>
//               <div className={styles.rightBottom}>
//                 <Image
//                   src="/map.png"
//                   width={1030}
//                   height={349}
//                   alt="img"
//                   style={{
//                     marginBottom: "43px",
//                   }}
//                 />
//                 <Image
//                   src="/courirInfo.png"
//                   width={1030}
//                   height={144}
//                   alt="img"
//                 />
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// function Orders() {
//   const [orders, setOrders] = useState([]);
//   useEffect(() => {
//     const savedOrders = localStorage.getItem("orders");
//     if (savedOrders) {
//       setOrders(JSON.parse(savedOrders));
//     }
//   }, []);

//   console.log(orders);
//   return (
//     <>
//       <Head>
//         <title>Orders Page {orderListData.userId}</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="container">
//         <div
//           style={{
//             width: "100%",
//           }}
//         >
//           <div
//             style={{
//               marginBottom: "40px",
//             }}
//           >
//             <div
//               style={{
//                 maxWidth: "1468px",
//                 display: "flex",
//                 alignItems: "center",
//                 justifyContent: "space-between",
//               }}
//             >
//               <PageTitle
//                 title="Order ID # "
//                 subtitle="Orders / Order Detaills"
//                 id={orders.userId}
//               />
//               <div>
//                 <button className={styles.cancelBtn}>Cancel Order</button>
//                 <button className={styles.onDelivery}>On Delivery</button>
//               </div>
//             </div>
//           </div>
//           <div style={{ display: "flex", alignItems: "start", gap: "40px" }}>
//             <div className={styles.leftDiv}>
//               <div className={styles.leftTop}>
//                 <div className={styles.forAvatar}></div>
//                 <h2>{orders.userName}</h2>
//                 <p className={styles.type}>{orders.type}</p>
//                 <div className={styles.noteOrder}>
//                   <h3>Note Order</h3>
//                   <p>
//                     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
//                     do eiusmod tempor incididunt ut labore et dolore magna
//                     aliqua.
//                   </p>
//                   <div className={styles.noteOrderDelivery}>
//                     <Image
//                       src="/shipping.png"
//                       alt="icon"
//                       width={50}
//                       height={50}
//                     />
//                     <p>
//                       6 The Avenue, London <br />
//                       EC50 4GN
//                     </p>
//                   </div>
//                 </div>
//               </div>
//               <div className={styles.leftBottom}>
//                 <Image
//                   src="/detailBottomLeft.png"
//                   width={211}
//                   height={366}
//                   alt="img"
//                 />
//               </div>
//             </div>
//             <div className={styles.rightDiv}>
//               <div className={styles.rightTop}>
//                 <CustomizedTables data={orders.orders} />
//               </div>
//               <div className={styles.rightBottom}>
//                 <Image
//                   src="/map.png"
//                   width={1030}
//                   height={349}
//                   alt="img"
//                   style={{
//                     marginBottom: "43px",
//                   }}
//                 />
//                 <Image
//                   src="/courirInfo.png"
//                   width={1030}
//                   height={144}
//                   alt="img"
//                 />
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// OrderDetail.getLayout = (pageProps) => (
//   <MainLayout>
//     <OrderDetail {...pageProps} />
//     <Orders {...pageProps} />
//   </MainLayout>
// );

// export default OrderDetail;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import { useParams } from "next/navigation";
import orderListData from "@/data";
import Head from "next/head";
import PageTitle from "@/components/common/PageTitle";
import MainLayout from "@/components/common/layouts/MainLayout";
import Image from "next/image";
import CustomizedTables from "@/components/common/detailTable";
import { useEffect, useState } from "react";
import Grid from "@mui/material/Grid";

function OrderDetail() {
  const route = useParams();
  const currentOrder = orderListData.find(
    (item) => item.userId === parseInt(route?.id)
  );
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    const savedOrders = localStorage.getItem("orders");
    if (savedOrders) {
      setOrders(JSON.parse(savedOrders));
    }
  }, []);

  return (
    <>
      <Head>
        <title>Orders Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div style={{ width: "100%" }}>
          <div style={{ marginBottom: "40px" }}>
            <Grid
              container
              justifyContent="space-between"
              alignItems="center"
              style={{ maxWidth: "1468px" }}
            >
              <PageTitle
                title="Order ID # "
                subtitle="Orders / Order Detaills"
                id={orders.userId}
              />
              <div>
                <button
                  style={{
                    padding: "18px 66px",
                    color: "#ff5b5b",
                    backgroundColor: "transparent",
                    border: "1px solid #ff5b5b",
                    borderRadius: "12px",
                  }}
                >
                  Cancel Order
                </button>
                <button
                  style={{
                    padding: "18px 66px",
                    color: "white",
                    background: "#00b074",
                    borderRadius: "12px",
                    marginLeft: "40px",
                    border: "none",
                  }}
                >
                  On Delivery
                </button>
              </div>
            </Grid>
          </div>

          <Grid container spacing={2} alignItems="flex-start">
            {/* LEFT SIDE */}
            <Grid size={3}>
              <div style={{ width: "339px" }}>
                <div
                  style={{
                    width: "339px",
                    height: "614px",
                    backgroundColor: "white",
                    borderRadius: "16px",
                    display: "flex",
                    alignItems: "center",
                    flexDirection: "column",
                  }}
                >
                  <div
                    style={{
                      backgroundColor: "#c4c4c4",
                      width: "160px",
                      height: "160px",
                      borderRadius: "50%",
                      marginTop: "30px",
                      marginBottom: "27px",
                    }}
                  ></div>
                  <h2
                    style={{
                      fontWeight: 600,
                      fontSize: "18px",
                      color: "#3e4954",
                      marginBottom: "10px",
                    }}
                  >
                    {orders.userName}
                  </h2>
                  <p
                    style={{
                      padding: "8px 22px",
                      backgroundColor: "#00b07426",
                      fontWeight: 600,
                      color: "#00b074",
                      borderRadius: "6px",
                      fontSize: "12px",
                      lineHeight: "18px",
                      marginBottom: "30px",
                    }}
                  >
                    {orders.type}
                  </p>

                  <div
                    style={{
                      maxWidth: "339px",
                      width: "100%",
                      minHeight: "297px",
                      borderRadius: "16px",
                      backgroundColor: "#5e6c93",
                      padding: "30px",
                      position: "relative",
                    }}
                  >
                    <h3
                      style={{
                        fontWeight: 700,
                        fontSize: "24px",
                        color: "#ffffff",
                        marginBottom: "20px",
                      }}
                    >
                      Note Order
                    </h3>
                    <p
                      style={{
                        fontWeight: 400,
                        fontSize: "14px",
                        lineHeight: "26px",
                        color: "#ffffffaf",
                      }}
                    >
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua.
                    </p>
                    <div
                      style={{
                        position: "absolute",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gap: "20px",
                        bottom: "-8px",
                        backgroundColor: "#2d9cdb",
                        padding: "30px",
                        borderRadius: "16px",
                        width: "100%",
                        left: 0,
                      }}
                    >
                      <Image
                        src="/shipping.png"
                        alt="icon"
                        width={50}
                        height={50}
                        style={{
                          padding: "11px 10px 10px 11px",
                          backgroundColor: "white",
                          borderRadius: "50%",
                        }}
                      />
                      <p
                        style={{
                          color: "#ffffff",
                          fontWeight: 600,
                          fontSize: "16px",
                          lineHeight: "26px",
                        }}
                      >
                        6 The Avenue, London <br />
                        EC50 4GN
                      </p>
                    </div>
                  </div>
                </div>

                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    width: "339px",
                    height: "471px",
                    backgroundColor: "white",
                    borderRadius: "16px",
                    marginTop: "40px",
                  }}
                >
                  <Image
                    src="/detailBottomLeft.png"
                    width={211}
                    height={366}
                    alt="img"
                  />
                </div>
              </div>
            </Grid>

            {/* RIGHT SIDE */}
            <Grid size={9}>
              <div
                style={{
                  width: "1089px",
                }}
              >
                <div
                  style={{
                    width: "1089px",
                    backgroundColor: "white",
                    borderRadius: "16px",
                  }}
                >
                  <CustomizedTables data={orders.orders} />
                </div>

                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexDirection: "column",
                    width: "1089px",
                    height: "599px",
                    backgroundColor: "white",
                    borderRadius: "16px",
                    marginTop: "40px",
                  }}
                >
                  <Image
                    src="/map.png"
                    width={1030}
                    height={349}
                    alt="img"
                    style={{ marginBottom: "43px" }}
                  />
                  <Image
                    src="/courirInfo.png"
                    width={1030}
                    height={144}
                    alt="img"
                  />
                </div>
              </div>
            </Grid>
          </Grid>
        </div>
      </div>
    </>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);

export default OrderDetail;
